// <auto-generated />
using System;
using DigitalServices.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigitalServices.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260829182130_AddCustomSoftwareService")]
    partial class AddCustomSoftwareService
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DigitalServices.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Clients_Email");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("DigitalServices.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("IX_Orders_ClientId");

                    b.HasIndex("ExternalReference")
                        .IsUnique()
                        .HasDatabaseName("UX_Orders_ExternalReference");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Orders_OrderNumber");

                    b.HasIndex("PackageId")
                        .HasDatabaseName("IX_Orders_PackageId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Orders_Status");

                    b.ToTable("Orders", null, t =>
                        {
                            t.HasCheckConstraint("CK_Orders_TotalAmount_Positive", "`TotalAmount` > 0");
                        });
                });

            modelBuilder.Entity("DigitalServices.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)");

                    b.Property<string>("Gateway")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GatewayPaymentId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("NotificationId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PreferenceId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RawPayload")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("StatusDetail")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_Payments_OrderId");

                    b.HasIndex("PreferenceId")
                        .HasDatabaseName("IX_Payments_PreferenceId");

                    b.HasIndex("Gateway", "GatewayPaymentId")
                        .IsUnique()
                        .HasDatabaseName("UX_Payments_Gateway_GatewayPaymentId");

                    b.HasIndex("Gateway", "NotificationId")
                        .IsUnique()
                        .HasDatabaseName("UX_Payments_Gateway_NotificationId");

                    b.ToTable("Payments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Payments_Amount_Positive", "`Amount` > 0");
                        });
                });

            modelBuilder.Entity("DigitalServices.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Services_IsActive");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UX_Services_Slug");

                    b.ToTable("Services", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sitios web rápidos, accesibles y preparados para crecer con tu negocio.",
                            IsActive = true,
                            Slug = "desarrollo-web",
                            Title = "Desarrollo Web",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Asistentes inteligentes conectados con los procesos y datos de tu empresa.",
                            IsActive = true,
                            Slug = "chatbots-con-ia",
                            Title = "Chatbots con IA",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Flujos automatizados que reducen tareas manuales y errores operativos.",
                            IsActive = true,
                            Slug = "automatizaciones",
                            Title = "Automatizaciones",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Soluciones digitales personalizadas para optimizar la operación y escala de tu negocio.",
                            IsActive = true,
                            Slug = "software-a-medida",
                            Title = "Software a Medida",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("DigitalServices.Domain.Entities.ServicePackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)");

                    b.Property<int>("DeliveryDays")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_ServicePackages_IsActive");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("IX_ServicePackages_ServiceId");

                    b.HasIndex("ServiceId", "IsActive")
                        .HasDatabaseName("IX_ServicePackages_ServiceId_IsActive");

                    b.ToTable("ServicePackages", null, t =>
                        {
                            t.HasCheckConstraint("CK_ServicePackages_DeliveryDays_Positive", "`DeliveryDays` > 0");

                            t.HasCheckConstraint("CK_ServicePackages_Price_Positive", "`Price` > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "PEN",
                            DeliveryDays = 10,
                            Description = "Página enfocada en conversión para una campaña o servicio.",
                            Features = "[\"Dise\\u00F1o responsive\",\"Formulario de contacto\",\"SEO t\\u00E9cnico inicial\"]",
                            IsActive = true,
                            Name = "Landing Page",
                            Price = 1200m,
                            ServiceId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "PEN",
                            DeliveryDays = 20,
                            Description = "Presencia web completa para presentar empresa, servicios y casos de éxito.",
                            Features = "[\"Hasta 8 secciones\",\"Panel de contenidos\",\"Anal\\u00EDtica b\\u00E1sica\"]",
                            IsActive = true,
                            Name = "Sitio Corporativo",
                            Price = 2800m,
                            ServiceId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "PEN",
                            DeliveryDays = 45,
                            Description = "Base a medida para procesos digitales con alcance definido en descubrimiento.",
                            Features = "[\"Descubrimiento t\\u00E9cnico\",\"Arquitectura escalable\",\"Despliegue inicial\"]",
                            IsActive = true,
                            Name = "Plataforma Personalizada",
                            Price = 6500m,
                            ServiceId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "PEN",
                            DeliveryDays = 14,
                            Description = "Asistente para preguntas frecuentes entrenado con contenido del negocio.",
                            Features = "[\"Base de conocimiento\",\"Widget web\",\"M\\u00E9tricas esenciales\"]",
                            IsActive = true,
                            Name = "Chatbot Básico",
                            Price = 1800m,
                            ServiceId = new Guid("10000000-0000-0000-0000-000000000002"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "PEN",
                            DeliveryDays = 30,
                            Description = "Asistente conectado con fuentes y flujos internos seleccionados.",
                            Features = "[\"Integraciones acordadas\",\"Escalamiento a humano\",\"Monitoreo\"]",
                            IsActive = true,
                            Name = "Chatbot Empresarial",
                            Price = 4800m,
                            ServiceId = new Guid("10000000-0000-0000-0000-000000000002"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "PEN",
                            DeliveryDays = 12,
                            Description = "Automatización de un flujo repetitivo claramente delimitado.",
                            Features = "[\"Un flujo\",\"Registro de ejecuci\\u00F3n\",\"Documentaci\\u00F3n operativa\"]",
                            IsActive = true,
                            Name = "Automatización Básica",
                            Price = 1400m,
                            ServiceId = new Guid("10000000-0000-0000-0000-000000000003"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "PEN",
                            DeliveryDays = 25,
                            Description = "Diseño e implementación de varios pasos e integraciones acordadas.",
                            Features = "[\"An\\u00E1lisis del proceso\",\"Integraciones personalizadas\",\"Alertas de fallos\"]",
                            IsActive = true,
                            Name = "Automatización Personalizada",
                            Price = 3900m,
                            ServiceId = new Guid("10000000-0000-0000-0000-000000000003"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "PEN",
                            DeliveryDays = 35,
                            Description = "Módulo o herramienta interna con alcance y requerimientos definidos.",
                            Features = "[\"Relevamiento de requisitos\",\"Arquitectura escalable\",\"Pruebas y despliegue\"]",
                            IsActive = true,
                            Name = "Software Estándar",
                            Price = 5500m,
                            ServiceId = new Guid("10000000-0000-0000-0000-000000000004"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "PEN",
                            DeliveryDays = 60,
                            Description = "Plataforma integral con múltiples módulos, integraciones y soporte.",
                            Features = "[\"Arquitectura empresarial\",\"Integraciones a medida\",\"Monitoreo y soporte\"]",
                            IsActive = true,
                            Name = "Software Empresarial",
                            Price = 12000m,
                            ServiceId = new Guid("10000000-0000-0000-0000-000000000004"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("DigitalServices.Infrastructure.Persistence.PaymentNotificationReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Gateway")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GatewayPaymentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("NotificationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("GatewayPaymentId")
                        .HasDatabaseName("IX_PaymentNotificationReceipts_GatewayPaymentId");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("IX_PaymentNotificationReceipts_PaymentId");

                    b.HasIndex("Gateway", "NotificationId")
                        .IsUnique()
                        .HasDatabaseName("UX_PaymentNotificationReceipts_Gateway_NotificationId");

                    b.ToTable("PaymentNotificationReceipts", (string)null);
                });

            modelBuilder.Entity("DigitalServices.Domain.Entities.Order", b =>
                {
                    b.HasOne("DigitalServices.Domain.Entities.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigitalServices.Domain.Entities.ServicePackage", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("DigitalServices.Domain.Entities.Payment", b =>
                {
                    b.HasOne("DigitalServices.Domain.Entities.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DigitalServices.Domain.Entities.ServicePackage", b =>
                {
                    b.HasOne("DigitalServices.Domain.Entities.Service", "Service")
                        .WithMany("Packages")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("DigitalServices.Infrastructure.Persistence.PaymentNotificationReceipt", b =>
                {
                    b.HasOne("DigitalServices.Domain.Entities.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("DigitalServices.Domain.Entities.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DigitalServices.Domain.Entities.Order", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("DigitalServices.Domain.Entities.Service", b =>
                {
                    b.Navigation("Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
